"""empty message

Revision ID: 19e869083406
Revises: 
Create Date: 2017-11-02 20:50:41.113042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19e869083406'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.Column('company_name', sa.String(length=120), nullable=True),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('amount_meetings', sa.Integer(), nullable=True),
    sa.Column('personnel_present', sa.Integer(), nullable=True),
    sa.Column('time_present', sa.String(length=100), nullable=True),
    sa.Column('company_strengths', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_name'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Applicants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_nature', sa.String(length=50), nullable=True),
    sa.Column('experience_in_years', sa.String(length=50), nullable=True),
    sa.Column('excellent_skills', sa.Text(), nullable=True),
    sa.Column('extra_skills', sa.Text(), nullable=True),
    sa.Column('skills_description', sa.String(length=1000), nullable=True),
    sa.Column('job_description', sa.String(length=1000), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Applicants')
    op.drop_table('Users')
    # ### end Alembic commands ###
