"""empty message

Revision ID: 74de074a0fe5
Revises: a6117675e847
Create Date: 2017-10-19 14:55:54.172419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74de074a0fe5'
down_revision = 'a6117675e847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'password',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=120),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'password',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###
